#include <iostream>
using namespace std;

// 下面两种写法都是该函数不抛出任何异常

void func1() throw()
{

}

void func2() noexcept
{

}

int main()
{

}
